from fastapi import FastAPI, UploadFile, File
from PIL import Image
from model import predict
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import FileResponse
from reportlab.lib.pagesizes import letter
from reportlab.pdfgen import canvas
import uuid

app = FastAPI()

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

@app.post("/predict")

async def predict_image(file: UploadFile = File(...)):

    image = Image.open(file.file)

    result = predict(image)

    return result

from pydantic import BaseModel
from fastapi.responses import StreamingResponse
from reportlab.pdfgen import canvas
import io

class ReportRequest(BaseModel):
    prediction: str
    confidence: float


@app.post("/generate-report")
async def generate_report(data: ReportRequest):

    buffer = io.BytesIO()

    p = canvas.Canvas(buffer)

    p.setFont("Helvetica", 20)
    p.drawString(100, 750, "AI Breast Cancer Analysis Report")

    p.setFont("Helvetica", 14)
    p.drawString(100, 700, f"Prediction: {data.prediction}")
    p.drawString(100, 670, f"Confidence: {data.confidence}%")

    p.drawString(100, 620, "Generated by AI Diagnostic Assistant")

    p.save()

    buffer.seek(0)

    return StreamingResponse(
        buffer,
        media_type="application/pdf",
        headers={
            "Content-Disposition": "attachment; filename=AI_Breast_Cancer_Report.pdf"
        }
    )